<a href="https://colab.research.google.com/github/fjpa121197/DataScienceDM/blob/master/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

1.Create a (4 x 2) integer array and print it's attributes

In [0]:
first_array = np.empty([4,2],dtype=np.int32)

In [0]:
print(type(first_array))
print(first_array.ndim)
print(first_array.shape)
print(first_array.itemsize)
print(first_array.nbytes)

<class 'numpy.ndarray'>
2
(4, 2)
4
32


In [0]:
print(first_array)

[[1 0]
 [1 0]
 [1 0]
 [0 0]]


2.Create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
second_array = np.empty([1,10],dtype=np.int16)
print(second_array)
sorted_ascending = np.sort(second_array)
print(sorted_ascending)
sorted_descending = -np.sort(-second_array)
print(sorted_descending)

[[28288  1193   105    40     0     0     0     0     0     0]]
[[    0     0     0     0     0     0    40   105  1193 28288]]
[[28288  1193   105    40     0     0     0     0     0     0]]


3.Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [0]:
third_array = np.arange(1,10)
third_array_n = third_array.reshape([3,3])
third_array_n

4.Stack two arrays of any size horizontally and vertically

In [0]:
fourth_array_1 = np.array([[2,3],[3,2]])
fourth_array_2 = np.array([[5,6]])
print(fourth_array_1)
print(fourth_array_2)
fourth_concat_1 = np.concatenate((fourth_array_1,fourth_array_2),axis = 0)
fourth_concat_2 = np.concatenate((fourth_array_1,fourth_array_2.T),axis = 1)
print(fourth_concat_1)
print(fourth_concat_2)

[[2 3]
 [3 2]]
[[5 6]]


5.Create two array of same size and find commom elements

In [0]:
fifth_array_1 = np.arange(1,10,2)
fifth_array_2 = np.arange(1,11,3)
print(fifth_array_1)
print(fifth_array_2)
np.intersect1d(fifth_array_1,fifth_array_2)

[1 3 5 7 9]
[ 1  4  7 10]


array([1, 7])

6.Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [0]:
sixth_array = np.random.random((5,5))
print(sixth_array)
min_sixth = sixth_array.min()
print(min_sixth)
max_sixth = sixth_array.max()
print(max_sixth)

[[0.82786769 0.93110713 0.0745966  0.4987093  0.70386829]
 [0.98357257 0.98010355 0.07328624 0.83742843 0.32320124]
 [0.62342566 0.48016811 0.18077824 0.03501108 0.01126717]
 [0.10073715 0.92713857 0.04578105 0.353887   0.916421  ]
 [0.61707269 0.08853664 0.0639699  0.70629561 0.34020858]]
0.011267170419579253
0.9835725663429681


7.Create an array of size 100 and compute the mean, median, standard deviation.

In [0]:
seventh_array = np.random.random((1,100))
print(seventh_array.size)
mean_seventh = seventh_array.mean()
median_seventh = np.median(seventh_array)
std_seventh = np.std(seventh_array)
print(mean_seventh,median_seventh,std_seventh)

100
0.46304394518199593 0.45535462137750543 0.2746448268014783


8.Normalize a 5x5 random matrix

In [0]:
eighth_matrix = np.random.random((5,5))
print(eighth_matrix)

[[0.61792405 0.40497434 0.85976771 0.69601829 0.99698232]
 [0.99056378 0.96894098 0.70052723 0.4178105  0.00178777]
 [0.0853502  0.88870505 0.21535266 0.67098505 0.8606311 ]
 [0.6702036  0.38764685 0.60927233 0.52386051 0.76100051]
 [0.44269504 0.18583967 0.08938243 0.77759179 0.16302052]]


Preguntar sobre standar scaler

In [0]:
xmax, xmin = eighth_matrix.max(), eighth_matrix.min()
eighth_matrix = (eighth_matrix - xmin)/(xmax - xmin)
print("After normalization:")
print(eighth_matrix)

After normalization:
[[0.61911139 0.40513342 0.86212283 0.69758272 1.        ]
 [0.99355047 0.97182326 0.70211343 0.41803157 0.        ]
 [0.08396593 0.8911999  0.21459613 0.6724286  0.86299039]
 [0.67164338 0.38772226 0.6104179  0.52459365 0.76287872]
 [0.44303626 0.18494063 0.08801763 0.77955011 0.16201129]]


9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?


In [0]:
last1_array= np.random.random((4,4,3))
last2_array= np.random.random((4,4))

In [0]:
print(last1_array)

[[[0.91415107 0.0024431  0.78855345]
  [0.28736717 0.6874105  0.28701784]
  [0.61526071 0.92105713 0.96071759]
  [0.27682621 0.95908228 0.62957496]]

 [[0.48399118 0.79658715 0.35044938]
  [0.88863417 0.06029217 0.23760366]
  [0.26233958 0.12210253 0.12279559]
  [0.86895318 0.84167299 0.29670549]]

 [[0.65411403 0.42195753 0.11594314]
  [0.20559794 0.10497207 0.43521465]
  [0.58807962 0.36896958 0.04378684]
  [0.71020441 0.47358365 0.21192831]]

 [[0.33195886 0.63476653 0.68784487]
  [0.12350879 0.95923623 0.16795745]
  [0.2013851  0.92674347 0.07405552]
  [0.75204598 0.98692393 0.75851162]]]


In [0]:
print(last2_array)

[[0.57419942 0.83871967 0.54041102 0.51750322]
 [0.13531231 0.67468379 0.81221461 0.55473337]
 [0.99528795 0.64693184 0.94693509 0.02141234]
 [0.8111919  0.29839346 0.21902584 0.00887703]]
