<a href="https://colab.research.google.com/github/fjpa121197/DataScienceDM/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn import preprocessing

1.Create a (4 x 2) integer array and print it's attributes

In [0]:
first_array = np.empty([4,2],dtype=np.int32)

In [0]:
print(type(first_array))
print(first_array.ndim)
print(first_array.shape)
print(first_array.itemsize)
print(first_array.nbytes)

<class 'numpy.ndarray'>
2
(4, 2)
4
32


In [0]:
print(first_array)

[[         0 1072693248]
 [         0 1072693248]
 [         0 1072693248]
 [         0          0]]


2.Create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
second_array = np.empty([1,10],dtype=np.int16)
print(second_array)
sorted_ascending = np.sort(second_array)
print(sorted_ascending)
sorted_descending = -np.sort(-second_array)
print(sorted_descending)

[[28288  1193   105    40     0     0     0     0     0     0]]
[[    0     0     0     0     0     0    40   105  1193 28288]]
[[28288  1193   105    40     0     0     0     0     0     0]]


3.Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [0]:
third_array = np.arange(1,10)
third_array_n = third_array.reshape([3,3])
third_array_n

4.Stack two arrays of any size horizontally and vertically

In [0]:
fourth_array_1 = np.array([[2,3],[3,2]])
fourth_array_2 = np.array([[5,6]])
print(fourth_array_1)
print(fourth_array_2)
fourth_concat_1 = np.concatenate((fourth_array_1,fourth_array_2),axis = 0)
fourth_concat_2 = np.concatenate((fourth_array_1,fourth_array_2.T),axis = 1)
print(fourth_concat_1)
print(fourth_concat_2)

[[2 3]
 [3 2]]
[[5 6]]


5.Create two array of same size and find commom elements

In [0]:
fifth_array_1 = np.arange(1,10,2)
fifth_array_2 = np.arange(1,11,3)
print(fifth_array_1)
print(fifth_array_2)
np.intersect1d(fifth_array_1,fifth_array_2)

[1 3 5 7 9]
[ 1  4  7 10]


array([1, 7])

6.Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [0]:
sixth_array = np.random.random((5,5))
print(sixth_array)
min_sixth = sixth_array.min()
print(min_sixth)
max_sixth = sixth_array.max()
print(max_sixth)

[[0.82786769 0.93110713 0.0745966  0.4987093  0.70386829]
 [0.98357257 0.98010355 0.07328624 0.83742843 0.32320124]
 [0.62342566 0.48016811 0.18077824 0.03501108 0.01126717]
 [0.10073715 0.92713857 0.04578105 0.353887   0.916421  ]
 [0.61707269 0.08853664 0.0639699  0.70629561 0.34020858]]
0.011267170419579253
0.9835725663429681


7.Create an array of size 100 and compute the mean, median, standard deviation.

In [0]:
seventh_array = np.random.random((1,100))
print(seventh_array.size)
mean_seventh = seventh_array.mean()
median_seventh = np.median(seventh_array)
std_seventh = np.std(seventh_array)
print(mean_seventh,median_seventh,std_seventh)

100
0.46304394518199593 0.45535462137750543 0.2746448268014783


8.Normalize a 5x5 random matrix

In [0]:
eighth_matrix = np.random.random((5,5))
print(eighth_matrix)
xmax, xmin = eighth_matrix.max(), eighth_matrix.min()
eighth_matrix = (eighth_matrix - xmin)/(xmax - xmin)
print("After normalization:")
print(eighth_matrix)
print("Credits to user from stackoverflow")

[[0.52264081 0.91376373 0.66730061 0.10323858 0.08698004]
 [0.30023966 0.14503927 0.56613273 0.8065983  0.33700743]
 [0.95757628 0.44136037 0.83871385 0.22308243 0.05657548]
 [0.53373661 0.71828826 0.53971111 0.71332518 0.46235294]
 [0.65868822 0.00401047 0.45987438 0.83676141 0.81225017]]
After normalization:
[[0.54388521 0.95405398 0.69558926 0.10406005 0.0870098 ]
 [0.31065416 0.14789624 0.58949498 0.8416701  0.34921235]
 [1.         0.4586468  0.87534953 0.22973974 0.05512468]
 [0.55552133 0.74905977 0.56178675 0.74385502 0.4806616 ]
 [0.68655749 0.         0.47806235 0.87330202 0.84759719]]
Credits to user from stackoverflow


In [0]:
lol = np.random.random((5,5))
print(lol)
lol_n = preprocessing.normalize(lol)
print(lol_n)

[[0.83384998 0.05727802 0.05997696 0.85606071 0.21012595]
 [0.2740144  0.6316511  0.45801616 0.5459629  0.65769879]
 [0.44377382 0.10499481 0.91372894 0.32266175 0.70672856]
 [0.23036904 0.54198051 0.63426229 0.33785866 0.20477509]
 [0.95327869 0.03416363 0.21156595 0.04578527 0.92235257]]
[[0.6856112  0.04709534 0.04931448 0.70387338 0.17277053]
 [0.23039529 0.53110143 0.38510665 0.45905354 0.55300271]
 [0.34585122 0.08182678 0.7121066  0.25146359 0.55078268]
 [0.24213411 0.56965975 0.66665442 0.35511329 0.21523307]
 [0.70905669 0.02541119 0.15736453 0.03405547 0.68605358]]


9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?


In [0]:
last1_array= np.random.random((4,4,3))
last2_array= np.random.random((4,4))

In [0]:
print(last1_array[0])

[[0.82044282 0.42676236 0.30461586]
 [0.55039547 0.501096   0.14933011]
 [0.74076894 0.81717986 0.72862606]
 [0.0203691  0.165292   0.51966846]]


In [0]:
print(last2_array)

[[0.01157211 0.73323779 0.40269645 0.23359737]
 [0.37616377 0.3820296  0.77911966 0.10495211]
 [0.54481157 0.79128162 0.61006972 0.6570205 ]
 [0.32086965 0.43066118 0.01940912 0.81689569]]


In [0]:
last_array=np.multiply(last1_array,last2_array[:,:,None])

In [0]:
print(last_array)

[[[0.00949425 0.00493854 0.00352505]
  [0.40357076 0.36742252 0.10949448]
  [0.29830502 0.32907543 0.29341513]
  [0.00475817 0.03861178 0.12139318]]

 [[0.08898149 0.0913772  0.05930961]
  [0.02514036 0.27718107 0.06950504]
  [0.62035182 0.10565557 0.19186292]
  [0.01203837 0.09694309 0.0867238 ]]

 [[0.16160263 0.32068824 0.29360633]
  [0.76202885 0.59518883 0.39426235]
  [0.36564292 0.48297915 0.48394033]
  [0.16479352 0.41513545 0.12714078]]

 [[0.00308105 0.04773749 0.06951499]
  [0.09939864 0.15296635 0.23039802]
  [0.01823059 0.00105899 0.00316378]
  [0.44882638 0.66073335 0.27464285]]]
