<a href="https://colab.research.google.com/github/fjpa121197/DataScienceDM/blob/master/Lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
#Credits to professor
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = new_arr[user_id][item_id]
                if not rating == 99.0:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        #if (iteration % 1000) == 0:
        print(mse)

In [97]:
#Read data
data_df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv",header=None)

data_df.drop(data_df.columns[0],axis = 1, inplace = True)
print(data_df)
arr = data_df.values
#There are cells that have a 99, which means that they have a null value/not rated
rated_cells = np.where(arr != 99)

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


In [86]:
print(arr)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]


In [98]:
new_arr, idx = replace(arr,0.1)
print(new_arr)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 99.   ... 99.   99.   99.  ]]


In [99]:
print(idx)

(array([  672, 24140, 18848, ..., 14875, 11082, 24507]), array([24, 13, 52, ..., 86, 51, 51]))


In [0]:
#Start of Latent Factor Modelling

n_latent_factors = 3

#Random values
latent_user_preferences = np.random.random((new_arr.shape[0], n_latent_factors))
latent_item_features = np.random.random((new_arr.shape[1], n_latent_factors))

In [120]:
sgd()

24.59717756667817
22.988005644724133
20.899147627735154
18.491972390486087
17.73496261494542
17.603924924806893
17.535394756235164
17.41980346274494
17.28716139046625
17.256379893067297


In [121]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-3.58370306, -5.12036302, -5.92562258, ..., -3.82144375,
        -6.06110151, -3.84940558],
       [ 2.89330651,  4.66387742,  4.29055974, ...,  3.91303375,
         2.80630735,  4.22913633],
       [ 7.08456034,  7.79072628,  8.06220706, ...,  8.74404145,
         8.54324893,  9.32040484],
       ...,
       [ 0.25304983,  2.890389  ,  1.11636702, ...,  1.68700018,
        -2.9146416 ,  2.13943359],
       [-1.84108757, -2.57245959, -3.24831489, ..., -1.74805095,
        -3.66767532, -1.683559  ],
       [ 3.83306048,  3.93865451,  3.92415174, ...,  4.87595399,
         4.20407542,  5.25107909]])

In [0]:
values = [zip(new_arr[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data_df.columns

In [125]:
comparison_data

1    ...                         100
0      (-7.82, -3.583703055010273)  ...  (99.0, -3.849405583689203)
1        (4.08, 2.893306509935147)  ...   (1.07, 4.229136331361211)
2        (99.0, 7.084560342541318)  ...   (99.0, 9.320404841055455)
3       (99.0, 2.4229831491492146)  ...   (99.0, 5.610415947413419)
4        (8.5, 3.3258885047796043)  ...    (1.6, 5.213401332762607)
...                            ...  ...                         ...
24978    (0.44, 3.998206384377643)  ...   (7.43, 5.839157814688478)
24979   (9.13, 1.8812321832205192)  ...  (8.45, 2.3231058680079624)
24980     (99.0, 0.25304982692314)  ...   (99.0, 2.139433589247022)
24981  (99.0, -1.8410875691518942)  ...  (99.0, -1.683559004133813)
24982      (2.43, 3.8330604764265)  ...   (99.0, 5.251079090080138)

[24983 rows x 100 columns]